# Generated by Django 5.1 on 2024-08-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_add_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_product',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
