# Generated by Django 5.1 on 2024-10-01 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_wishlistitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='Add_product',
            new_name='product',
        ),
    ]
