# Generated by Django 5.1 on 2024-10-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_wallet_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash on delevery', 'Cash on Delivery'), ('razorpay', 'Razorpay'), ('paypal', 'PayPal')], max_length=20, null=True),
        ),
    ]
