# Generated by Django 5.1 on 2024-10-17 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_offer_alter_transaction_timestamp_categoryoffer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash on delivery', 'Cash on Delivery'), ('razorpay', 'Razorpay'), ('paypal', 'PayPal')], max_length=20, null=True),
        ),
    ]
