# Generated by Django 5.1 on 2024-11-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_alter_orderstatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('purchased', 'Purchased'), ('returned', 'Returned')], default='purchased', max_length=20),
        ),
    ]
