# Generated by Django 5.1 on 2024-11-25 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_order_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
    ]
