# Generated by Django 5.1 on 2024-11-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_remove_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
